name: Generate pot files

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "compass/*.py"

jobs:
  generate_pot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run generating .pot scripts
        run: |
          for file in ./compass/*.py; do
              basename=${file##*/}
              domain=${basename%.*}
              python i18n/pygettext.py -d $domain -p compass/locale $file
          done

      - name: Push to master
        run: |
          git add -N compass/locale/*.pot
          if ! git diff --exit-code --quiet
          then
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git add compass/locale/*.pot
            git commit -m "[actions] Update pot files"
            git push
          fi
